version: 1
update_configs:
  - package_manager: "java:gradle"
    directory: "/project"
    update_schedule: "daily"
    default_assignees:
    - growse
    allowed_updates:
    - match:
        update_type: "all"
